import { z } from "zod";
import { useQuery, queryOptions } from "@tanstack/react-query";
import { apiFetch, buildUrl } from "@/lib/api/client";

export type UseGetApiV1QueryWebAnalyticsEventsAggregateArgs = {
  projectId: string;
  by: Array<
    | "hour"
    | "day"
    | "week"
    | "month"
    | "year"
    | "country"
    | "deviceType"
    | "environment"
    | "requestPath"
    | "referrerHostname"
    | "osName"
    | "browserName"
    | "route"
    | "utmSource"
    | "utmMedium"
    | "utmCampaign"
    | "utmContent"
    | "utmTerm"
    | "eventName"
    | "flags"
    | "eventData"
    | string
  >;
  since: number | string;
  until: number | string;
  limit?: number | undefined;
  filter?: string | undefined;
  teamId?: string | undefined;
  slug?: string | undefined;
};

export const useGetApiV1QueryWebAnalyticsEventsAggregateResponse = z.object({
  version: z.number(),
  query: z.object({
    since: z.string(),
    until: z.string(),
    groupBy: z
      .array(
        z.union([
          z.string(),
          z.enum([
            "browserName",
            "country",
            "deviceType",
            "environment",
            "eventData",
            "eventName",
            "flags",
            "osName",
            "referrerHostname",
            "requestPath",
            "route",
            "utmCampaign",
            "utmContent",
            "utmMedium",
            "utmSource",
            "utmTerm",
          ]),
        ]),
      )
      .optional(),
    filter: z.string().optional(),
    limit: z.number(),
  }),
  data: z.union([
    z.array(
      z.object({
        projectId: z.string().optional(),
        country: z.string().optional(),
        deviceType: z.string().optional(),
        environment: z.string().optional(),
        requestPath: z.string().optional(),
        referrerHostname: z.string().optional(),
        osName: z.string().optional(),
        browserName: z.string().optional(),
        route: z.string().optional(),
        utmSource: z.string().optional(),
        utmMedium: z.string().optional(),
        utmCampaign: z.string().optional(),
        utmContent: z.string().optional(),
        utmTerm: z.string().optional(),
        flags: z.string().optional(),
        errorMessage: z.string().optional(),
        entryRevalidateSeconds: z.string().optional(),
        projectName: z.string().optional(),
        deploymentId: z.string().optional(),
        pathType: z.string().optional(),
        pathTypeVariant: z.string().optional(),
        requestHostname: z.string().optional(),
        requestResolvedIp: z.string().optional(),
        requestMethod: z.string().optional(),
        requestExtension: z.string().optional(),
        requestId: z.string().optional(),
        requestApi: z.string().optional(),
        referrerUrl: z.string().optional(),
        serverActionName: z.string().optional(),
        httpStatus: z.string().optional(),
        errorCode: z.string().optional(),
        source: z.string().optional(),
        edgeType: z.string().optional(),
        reason: z.string().optional(),
        edgeNetworkRegion: z.string().optional(),
        functionRegion: z.string().optional(),
        imageTransformationRegion: z.string().optional(),
        dataCacheRegion: z.string().optional(),
        cause: z.string().optional(),
        runtime: z.string().optional(),
        provider: z.string().optional(),
        isrCacheRegion: z.string().optional(),
        isrAction: z.string().optional(),
        cacheResult: z.string().optional(),
        cacheOperation: z.string().optional(),
        cacheHostname: z.string().optional(),
        cachePath: z.string().optional(),
        cacheHitState: z.string().optional(),
        cacheHitLevel: z.string().optional(),
        cacheApi: z.string().optional(),
        cacheReason: z.string().optional(),
        pprState: z.string().optional(),
        clientIp: z.string().optional(),
        clientIpCountry: z.string().optional(),
        clientUserAgent: z.string().optional(),
        httpAccept: z.string().optional(),
        clientJa4Digest: z.string().optional(),
        asnId: z.string().optional(),
        asnName: z.string().optional(),
        botName: z.string().optional(),
        botCategory: z.string().optional(),
        botCategoryLegacy: z.string().optional(),
        botVerified: z.string().optional(),
        botCheckResult: z.string().optional(),
        deepAnalysisCheck: z.string().optional(),
        wafAction: z.string().optional(),
        wafRuleId: z.string().optional(),
        ruleCategory: z.string().optional(),
        skewProtection: z.string().optional(),
        functionStartType: z.string().optional(),
        functionDispatcher: z.string().optional(),
        isAdditionalRequest: z.string().optional(),
        originHostname: z.string().optional(),
        originPath: z.string().optional(),
        originRoute: z.string().optional(),
        fetchType: z.string().optional(),
        fetchIndex: z.string().optional(),
        imageSource: z.string().optional(),
        sourceImage: z.string().optional(),
        sourceImagePathname: z.string().optional(),
        sourceImageHostname: z.string().optional(),
        sourceImageHash: z.string().optional(),
        optimizedQuality: z.string().optional(),
        optimizedWidthPixels: z.string().optional(),
        optimizedFormatMimeType: z.string().optional(),
        vdcOperationOrigin: z.string().optional(),
        entryName: z.string().optional(),
        entryId: z.string().optional(),
        entryItemId: z.string().optional(),
        tagName: z.string().optional(),
        cacheTags: z.string().optional(),
        storeId: z.string().optional(),
        storeName: z.string().optional(),
        blobOperationType: z.string().optional(),
        blobOperationLevel: z.string().optional(),
        visitorId: z.string().optional(),
        eventName: z.string().optional(),
        attributionTarget: z.string().optional(),
        attributionEventName: z.string().optional(),
        metricName: z.string().optional(),
        attributes: z.string().optional(),
        flagKey: z.string().optional(),
        flagVariant: z.string().optional(),
        flagEvaluationReason: z.string().optional(),
        flagClientName: z.string().optional(),
        sdkKeyId: z.string().optional(),
        sdkKeyEnvironment: z.string().optional(),
        reportingProjectId: z.string().optional(),
        reportingProjectName: z.string().optional(),
        eventData: z.string().optional(),
        middlewareAction: z.string().optional(),
        middlewareActionTarget: z.string().optional(),
        aiModel: z.string().optional(),
        aiGatewayModelId: z.string().optional(),
        aiProvider: z.string().optional(),
        aiModelType: z.string().optional(),
        servedSpeed: z.string().optional(),
        virtualModelSlug: z.string().optional(),
        virtualModelKind: z.string().optional(),
        inferenceEndpointSlug: z.string().optional(),
        inferenceScope: z.string().optional(),
        inferenceGeoRegion: z.string().optional(),
        inferenceProviderRegion: z.string().optional(),
        requestedInferenceRegion: z.string().optional(),
        costCurrency: z.string().optional(),
        marketCostCurrency: z.string().optional(),
        cachedInputTokensCurrency: z.string().optional(),
        cacheCreationInputTokensCurrency: z.string().optional(),
        cacheCreation1hInputTokensCurrency: z.string().optional(),
        surchargeCostCurrency: z.string().optional(),
        gatewayCostCurrency: z.string().optional(),
        keyId: z.string().optional(),
        keyName: z.string().optional(),
        authMethod: z.string().optional(),
        appName: z.string().optional(),
        codingAgent: z.string().optional(),
        isByok: z.string().optional(),
        spendAttribution: z.string().optional(),
        isPrivateModel: z.string().optional(),
        isRequestZdr: z.string().optional(),
        hipaaRequested: z.string().optional(),
        quotaRequested: z.string().optional(),
        quotaEntityId: z.string().optional(),
        quotaEntityType: z.string().optional(),
        videoResolution: z.string().optional(),
        videoAspectRatio: z.string().optional(),
        piiRedactionApplied: z.string().optional(),
        moderationApplied: z.string().optional(),
        queueName: z.string().optional(),
        consumerGroup: z.string().optional(),
        messageId: z.string().optional(),
        eventType: z.string().optional(),
        notificationUrl: z.string().optional(),
        queueRegion: z.string().optional(),
        sandboxSessionId: z.string().optional(),
        sandboxName: z.string().optional(),
        workflowRunId: z.string().optional(),
        workflowName: z.string().optional(),
        workflowStatus: z.string().optional(),
        stepRunId: z.string().optional(),
        workflowStepName: z.string().optional(),
        workflowEventType: z.string().optional(),
        region: z.string().optional(),
        specVersion: z.string().optional(),
        contentType: z.string().optional(),
        rewriteDestinationHostname: z.string().optional(),
        externalRewriteTargetHost: z.string().optional(),
        externalRewriteTargetPath: z.string().optional(),
        commitSha: z.string().optional(),
        reviewConclusion: z.string().optional(),
        pullRequestNumber: z.string().optional(),
        repositoryName: z.string().optional(),
        repositoryOwner: z.string().optional(),
        reviewStatus: z.string().optional(),
        pullRequestState: z.string().optional(),
        triggeringTag: z.string().optional(),
        redirectLocation: z.string().optional(),
        microfrontendsResponseReason: z.string().optional(),
        microfrontendsMatchedPath: z.string().optional(),
        microfrontendsDefaultAppDeploymentId: z.string().optional(),
        microfrontendsDefaultAppProjectId: z.string().optional(),
        service: z.string().optional(),
        isPrefetchRequest: z.string().optional(),
        spendReportGroupBy: z.string().optional(),
        spendReportDatePart: z.string().optional(),
        providerAttemptCanonicalSlug: z.string().optional(),
        providerAttemptCredentialType: z.string().optional(),
        providerAttemptSuccess: z.string().optional(),
        providerAttemptStatusCode: z.string().optional(),
        providerAttemptTimeout: z.string().optional(),
        providerAttemptIsFinal: z.string().optional(),
        providerAttemptNumber: z.string().optional(),
        providerAttemptTotalInRequest: z.string().optional(),
        generationId: z.string().optional(),
        sessionId: z.string().optional(),
        contentCaptureStatus: z.string().optional(),
        contentCaptureInputs: z.string().optional(),
        contentCaptureOutputs: z.string().optional(),
        transcriptStatus: z.string().optional(),
        transcriptInputs: z.string().optional(),
        transcriptOutputs: z.string().optional(),
        providerAttemptError: z.string().optional(),
        providerAttemptSafetyIdentifier: z.string().optional(),
        providerAttemptDevSafetyIdentifier: z.string().optional(),
        providerAttemptRegion: z.string().optional(),
        providerAttemptModelIndex: z.string().optional(),
        toolCallType: z.string().optional(),
        toolCallProvider: z.string().optional(),
        toolCallSuccess: z.string().optional(),
        toolCallErrorType: z.string().optional(),
        toolCallStatusCode: z.string().optional(),
        environmentId: z.string().optional(),
        billableRegion: z.string().optional(),
        direction: z.string().optional(),
        networkTenancy: z.string().optional(),
        trafficSource: z.string().optional(),
        networkId: z.string().optional(),
        privatelinkEndpointId: z.string().optional(),
        privatelinkDnsName: z.string().optional(),
        privatelinkIpAddress: z.string().optional(),
        timestamp: z.string(),
      }),
    ),
    z.array(
      z
        .object({
          projectId: z.string(),
          country: z.string(),
          deviceType: z.string(),
          environment: z.string(),
          requestPath: z.string(),
          referrerHostname: z.string(),
          osName: z.string(),
          browserName: z.string(),
          route: z.string(),
          utmSource: z.string(),
          utmMedium: z.string(),
          utmCampaign: z.string(),
          utmContent: z.string(),
          utmTerm: z.string(),
          flags: z.string(),
          errorMessage: z.string(),
          entryRevalidateSeconds: z.string(),
          projectName: z.string(),
          deploymentId: z.string(),
          pathType: z.string(),
          pathTypeVariant: z.string(),
          requestHostname: z.string(),
          requestResolvedIp: z.string(),
          requestMethod: z.string(),
          requestExtension: z.string(),
          requestId: z.string(),
          requestApi: z.string(),
          referrerUrl: z.string(),
          serverActionName: z.string(),
          httpStatus: z.string(),
          errorCode: z.string(),
          source: z.string(),
          edgeType: z.string(),
          reason: z.string(),
          edgeNetworkRegion: z.string(),
          functionRegion: z.string(),
          imageTransformationRegion: z.string(),
          dataCacheRegion: z.string(),
          cause: z.string(),
          runtime: z.string(),
          provider: z.string(),
          isrCacheRegion: z.string(),
          isrAction: z.string(),
          cacheResult: z.string(),
          cacheOperation: z.string(),
          cacheHostname: z.string(),
          cachePath: z.string(),
          cacheHitState: z.string(),
          cacheHitLevel: z.string(),
          cacheApi: z.string(),
          cacheReason: z.string(),
          pprState: z.string(),
          clientIp: z.string(),
          clientIpCountry: z.string(),
          clientUserAgent: z.string(),
          httpAccept: z.string(),
          clientJa4Digest: z.string(),
          asnId: z.string(),
          asnName: z.string(),
          botName: z.string(),
          botCategory: z.string(),
          botCategoryLegacy: z.string(),
          botVerified: z.string(),
          botCheckResult: z.string(),
          deepAnalysisCheck: z.string(),
          wafAction: z.string(),
          wafRuleId: z.string(),
          ruleCategory: z.string(),
          skewProtection: z.string(),
          functionStartType: z.string(),
          functionDispatcher: z.string(),
          isAdditionalRequest: z.string(),
          originHostname: z.string(),
          originPath: z.string(),
          originRoute: z.string(),
          fetchType: z.string(),
          fetchIndex: z.string(),
          imageSource: z.string(),
          sourceImage: z.string(),
          sourceImagePathname: z.string(),
          sourceImageHostname: z.string(),
          sourceImageHash: z.string(),
          optimizedQuality: z.string(),
          optimizedWidthPixels: z.string(),
          optimizedFormatMimeType: z.string(),
          vdcOperationOrigin: z.string(),
          entryName: z.string(),
          entryId: z.string(),
          entryItemId: z.string(),
          tagName: z.string(),
          cacheTags: z.string(),
          storeId: z.string(),
          storeName: z.string(),
          blobOperationType: z.string(),
          blobOperationLevel: z.string(),
          visitorId: z.string(),
          eventName: z.string(),
          attributionTarget: z.string(),
          attributionEventName: z.string(),
          metricName: z.string(),
          attributes: z.string(),
          flagKey: z.string(),
          flagVariant: z.string(),
          flagEvaluationReason: z.string(),
          flagClientName: z.string(),
          sdkKeyId: z.string(),
          sdkKeyEnvironment: z.string(),
          reportingProjectId: z.string(),
          reportingProjectName: z.string(),
          eventData: z.string(),
          middlewareAction: z.string(),
          middlewareActionTarget: z.string(),
          aiModel: z.string(),
          aiGatewayModelId: z.string(),
          aiProvider: z.string(),
          aiModelType: z.string(),
          servedSpeed: z.string(),
          virtualModelSlug: z.string(),
          virtualModelKind: z.string(),
          inferenceEndpointSlug: z.string(),
          inferenceScope: z.string(),
          inferenceGeoRegion: z.string(),
          inferenceProviderRegion: z.string(),
          requestedInferenceRegion: z.string(),
          costCurrency: z.string(),
          marketCostCurrency: z.string(),
          cachedInputTokensCurrency: z.string(),
          cacheCreationInputTokensCurrency: z.string(),
          cacheCreation1hInputTokensCurrency: z.string(),
          surchargeCostCurrency: z.string(),
          gatewayCostCurrency: z.string(),
          keyId: z.string(),
          keyName: z.string(),
          authMethod: z.string(),
          appName: z.string(),
          codingAgent: z.string(),
          isByok: z.string(),
          spendAttribution: z.string(),
          isPrivateModel: z.string(),
          isRequestZdr: z.string(),
          hipaaRequested: z.string(),
          quotaRequested: z.string(),
          quotaEntityId: z.string(),
          quotaEntityType: z.string(),
          videoResolution: z.string(),
          videoAspectRatio: z.string(),
          piiRedactionApplied: z.string(),
          moderationApplied: z.string(),
          queueName: z.string(),
          consumerGroup: z.string(),
          messageId: z.string(),
          eventType: z.string(),
          notificationUrl: z.string(),
          queueRegion: z.string(),
          sandboxSessionId: z.string(),
          sandboxName: z.string(),
          workflowRunId: z.string(),
          workflowName: z.string(),
          workflowStatus: z.string(),
          stepRunId: z.string(),
          workflowStepName: z.string(),
          workflowEventType: z.string(),
          region: z.string(),
          specVersion: z.string(),
          contentType: z.string(),
          rewriteDestinationHostname: z.string(),
          externalRewriteTargetHost: z.string(),
          externalRewriteTargetPath: z.string(),
          commitSha: z.string(),
          reviewConclusion: z.string(),
          pullRequestNumber: z.string(),
          repositoryName: z.string(),
          repositoryOwner: z.string(),
          reviewStatus: z.string(),
          pullRequestState: z.string(),
          triggeringTag: z.string(),
          redirectLocation: z.string(),
          microfrontendsResponseReason: z.string(),
          microfrontendsMatchedPath: z.string(),
          microfrontendsDefaultAppDeploymentId: z.string(),
          microfrontendsDefaultAppProjectId: z.string(),
          service: z.string(),
          isPrefetchRequest: z.string(),
          spendReportGroupBy: z.string(),
          spendReportDatePart: z.string(),
          providerAttemptCanonicalSlug: z.string(),
          providerAttemptCredentialType: z.string(),
          providerAttemptSuccess: z.string(),
          providerAttemptStatusCode: z.string(),
          providerAttemptTimeout: z.string(),
          providerAttemptIsFinal: z.string(),
          providerAttemptNumber: z.string(),
          providerAttemptTotalInRequest: z.string(),
          generationId: z.string(),
          sessionId: z.string(),
          contentCaptureStatus: z.string(),
          contentCaptureInputs: z.string(),
          contentCaptureOutputs: z.string(),
          transcriptStatus: z.string(),
          transcriptInputs: z.string(),
          transcriptOutputs: z.string(),
          providerAttemptError: z.string(),
          providerAttemptSafetyIdentifier: z.string(),
          providerAttemptDevSafetyIdentifier: z.string(),
          providerAttemptRegion: z.string(),
          providerAttemptModelIndex: z.string(),
          toolCallType: z.string(),
          toolCallProvider: z.string(),
          toolCallSuccess: z.string(),
          toolCallErrorType: z.string(),
          toolCallStatusCode: z.string(),
          environmentId: z.string(),
          billableRegion: z.string(),
          direction: z.string(),
          networkTenancy: z.string(),
          trafficSource: z.string(),
          networkId: z.string(),
          privatelinkEndpointId: z.string(),
          privatelinkDnsName: z.string(),
          privatelinkIpAddress: z.string(),
        })
        .and(z.record(z.string(), z.number().nullable())),
    ),
  ]),
});

export const getApiV1QueryWebAnalyticsEventsAggregateQueryOptions = (
  args: UseGetApiV1QueryWebAnalyticsEventsAggregateArgs,
) =>
  queryOptions({
    queryKey: [
      "GET /v1/query/web-analytics/events/aggregate",
      "web-analytics",
      args.projectId,
      args.by,
      args.since,
      args.until,
      args.limit,
      args.filter,
      args.teamId,
      args.slug,
    ],
    queryFn: () =>
      apiFetch(
        buildUrl("/v1/query/web-analytics/events/aggregate", {
          projectId: args.projectId,
          by: args.by,
          since: args.since,
          until: args.until,
          limit: args.limit,
          filter: args.filter,
          teamId: args.teamId,
          slug: args.slug,
        }),
        useGetApiV1QueryWebAnalyticsEventsAggregateResponse,
        { method: "GET" },
      ),
  });

export const useGetApiV1QueryWebAnalyticsEventsAggregate = (
  args: UseGetApiV1QueryWebAnalyticsEventsAggregateArgs,
) => useQuery(getApiV1QueryWebAnalyticsEventsAggregateQueryOptions(args));
