import { z } from "zod";
import { useQuery, queryOptions } from "@tanstack/react-query";
import { apiFetch, buildUrl } from "@/lib/api/client";

export type UseGetApiV1QueryWebAnalyticsVisitsCountArgs = {
  projectId: string;
  since?: (number | string) | undefined;
  until?: (number | string) | undefined;
  filter?: string | undefined;
  teamId?: string | undefined;
  slug?: string | undefined;
};

export const useGetApiV1QueryWebAnalyticsVisitsCountResponse = z.object({
  version: z.number(),
  query: z.object({ since: z.string(), until: z.string(), filter: z.string().optional() }),
  data: z.union([
    z
      .object({
        projectId: z.string(),
        country: z.string(),
        deviceType: z.string(),
        environment: z.string(),
        requestPath: z.string(),
        referrerHostname: z.string(),
        osName: z.string(),
        browserName: z.string(),
        route: z.string(),
        utmSource: z.string(),
        utmMedium: z.string(),
        utmCampaign: z.string(),
        utmContent: z.string(),
        utmTerm: z.string(),
        flags: z.string(),
        errorMessage: z.string(),
        entryRevalidateSeconds: z.string(),
        projectName: z.string(),
        deploymentId: z.string(),
        pathType: z.string(),
        pathTypeVariant: z.string(),
        requestHostname: z.string(),
        requestResolvedIp: z.string(),
        requestMethod: z.string(),
        requestExtension: z.string(),
        requestId: z.string(),
        requestApi: z.string(),
        referrerUrl: z.string(),
        serverActionName: z.string(),
        httpStatus: z.string(),
        errorCode: z.string(),
        source: z.string(),
        edgeType: z.string(),
        reason: z.string(),
        edgeNetworkRegion: z.string(),
        functionRegion: z.string(),
        imageTransformationRegion: z.string(),
        dataCacheRegion: z.string(),
        cause: z.string(),
        runtime: z.string(),
        provider: z.string(),
        isrCacheRegion: z.string(),
        isrAction: z.string(),
        cacheResult: z.string(),
        cacheOperation: z.string(),
        cacheHostname: z.string(),
        cachePath: z.string(),
        cacheHitState: z.string(),
        cacheHitLevel: z.string(),
        cacheApi: z.string(),
        cacheReason: z.string(),
        pprState: z.string(),
        clientIp: z.string(),
        clientIpCountry: z.string(),
        clientUserAgent: z.string(),
        httpAccept: z.string(),
        clientJa4Digest: z.string(),
        asnId: z.string(),
        asnName: z.string(),
        botName: z.string(),
        botCategory: z.string(),
        botCategoryLegacy: z.string(),
        botVerified: z.string(),
        botCheckResult: z.string(),
        deepAnalysisCheck: z.string(),
        wafAction: z.string(),
        wafRuleId: z.string(),
        ruleCategory: z.string(),
        skewProtection: z.string(),
        functionStartType: z.string(),
        functionDispatcher: z.string(),
        isAdditionalRequest: z.string(),
        originHostname: z.string(),
        originPath: z.string(),
        originRoute: z.string(),
        fetchType: z.string(),
        fetchIndex: z.string(),
        imageSource: z.string(),
        sourceImage: z.string(),
        sourceImagePathname: z.string(),
        sourceImageHostname: z.string(),
        sourceImageHash: z.string(),
        optimizedQuality: z.string(),
        optimizedWidthPixels: z.string(),
        optimizedFormatMimeType: z.string(),
        vdcOperationOrigin: z.string(),
        entryName: z.string(),
        entryId: z.string(),
        entryItemId: z.string(),
        tagName: z.string(),
        cacheTags: z.string(),
        storeId: z.string(),
        storeName: z.string(),
        blobOperationType: z.string(),
        blobOperationLevel: z.string(),
        visitorId: z.string(),
        eventName: z.string(),
        attributionTarget: z.string(),
        attributionEventName: z.string(),
        metricName: z.string(),
        attributes: z.string(),
        flagKey: z.string(),
        flagVariant: z.string(),
        flagEvaluationReason: z.string(),
        flagClientName: z.string(),
        sdkKeyId: z.string(),
        sdkKeyEnvironment: z.string(),
        reportingProjectId: z.string(),
        reportingProjectName: z.string(),
        eventData: z.string(),
        middlewareAction: z.string(),
        middlewareActionTarget: z.string(),
        aiModel: z.string(),
        aiGatewayModelId: z.string(),
        aiProvider: z.string(),
        aiModelType: z.string(),
        servedSpeed: z.string(),
        virtualModelSlug: z.string(),
        virtualModelKind: z.string(),
        inferenceEndpointSlug: z.string(),
        inferenceScope: z.string(),
        inferenceGeoRegion: z.string(),
        inferenceProviderRegion: z.string(),
        requestedInferenceRegion: z.string(),
        costCurrency: z.string(),
        marketCostCurrency: z.string(),
        cachedInputTokensCurrency: z.string(),
        cacheCreationInputTokensCurrency: z.string(),
        cacheCreation1hInputTokensCurrency: z.string(),
        surchargeCostCurrency: z.string(),
        gatewayCostCurrency: z.string(),
        keyId: z.string(),
        keyName: z.string(),
        authMethod: z.string(),
        appName: z.string(),
        codingAgent: z.string(),
        isByok: z.string(),
        spendAttribution: z.string(),
        isPrivateModel: z.string(),
        isRequestZdr: z.string(),
        hipaaRequested: z.string(),
        quotaRequested: z.string(),
        quotaEntityId: z.string(),
        quotaEntityType: z.string(),
        videoResolution: z.string(),
        videoAspectRatio: z.string(),
        piiRedactionApplied: z.string(),
        moderationApplied: z.string(),
        queueName: z.string(),
        consumerGroup: z.string(),
        messageId: z.string(),
        eventType: z.string(),
        notificationUrl: z.string(),
        queueRegion: z.string(),
        sandboxSessionId: z.string(),
        sandboxName: z.string(),
        workflowRunId: z.string(),
        workflowName: z.string(),
        workflowStatus: z.string(),
        stepRunId: z.string(),
        workflowStepName: z.string(),
        workflowEventType: z.string(),
        region: z.string(),
        specVersion: z.string(),
        contentType: z.string(),
        rewriteDestinationHostname: z.string(),
        externalRewriteTargetHost: z.string(),
        externalRewriteTargetPath: z.string(),
        commitSha: z.string(),
        reviewConclusion: z.string(),
        pullRequestNumber: z.string(),
        repositoryName: z.string(),
        repositoryOwner: z.string(),
        reviewStatus: z.string(),
        pullRequestState: z.string(),
        triggeringTag: z.string(),
        redirectLocation: z.string(),
        microfrontendsResponseReason: z.string(),
        microfrontendsMatchedPath: z.string(),
        microfrontendsDefaultAppDeploymentId: z.string(),
        microfrontendsDefaultAppProjectId: z.string(),
        service: z.string(),
        isPrefetchRequest: z.string(),
        spendReportGroupBy: z.string(),
        spendReportDatePart: z.string(),
        providerAttemptCanonicalSlug: z.string(),
        providerAttemptCredentialType: z.string(),
        providerAttemptSuccess: z.string(),
        providerAttemptStatusCode: z.string(),
        providerAttemptTimeout: z.string(),
        providerAttemptIsFinal: z.string(),
        providerAttemptNumber: z.string(),
        providerAttemptTotalInRequest: z.string(),
        generationId: z.string(),
        sessionId: z.string(),
        contentCaptureStatus: z.string(),
        contentCaptureInputs: z.string(),
        contentCaptureOutputs: z.string(),
        transcriptStatus: z.string(),
        transcriptInputs: z.string(),
        transcriptOutputs: z.string(),
        providerAttemptError: z.string(),
        providerAttemptSafetyIdentifier: z.string(),
        providerAttemptDevSafetyIdentifier: z.string(),
        providerAttemptRegion: z.string(),
        providerAttemptModelIndex: z.string(),
        toolCallType: z.string(),
        toolCallProvider: z.string(),
        toolCallSuccess: z.string(),
        toolCallErrorType: z.string(),
        toolCallStatusCode: z.string(),
        environmentId: z.string(),
        billableRegion: z.string(),
        direction: z.string(),
        networkTenancy: z.string(),
        trafficSource: z.string(),
        networkId: z.string(),
        privatelinkEndpointId: z.string(),
        privatelinkDnsName: z.string(),
        privatelinkIpAddress: z.string(),
      })
      .and(z.record(z.string(), z.number().nullable())),
    z.object({ visitors: z.number(), pageviews: z.number() }),
  ]),
});

export const getApiV1QueryWebAnalyticsVisitsCountQueryOptions = (
  args: UseGetApiV1QueryWebAnalyticsVisitsCountArgs,
) =>
  queryOptions({
    queryKey: [
      "GET /v1/query/web-analytics/visits/count",
      "web-analytics",
      args.projectId,
      args.since,
      args.until,
      args.filter,
      args.teamId,
      args.slug,
    ],
    queryFn: () =>
      apiFetch(
        buildUrl("/v1/query/web-analytics/visits/count", {
          projectId: args.projectId,
          since: args.since,
          until: args.until,
          filter: args.filter,
          teamId: args.teamId,
          slug: args.slug,
        }),
        useGetApiV1QueryWebAnalyticsVisitsCountResponse,
        { method: "GET" },
      ),
  });

export const useGetApiV1QueryWebAnalyticsVisitsCount = (
  args: UseGetApiV1QueryWebAnalyticsVisitsCountArgs,
) => useQuery(getApiV1QueryWebAnalyticsVisitsCountQueryOptions(args));
