import { z } from "zod";
import { useQuery, queryOptions } from "@tanstack/react-query";
import { apiFetch, buildUrl } from "@/lib/api/client";

export type UseGetApiV1WebhooksArgs = {
  projectId?: string | undefined;
  teamId?: string | undefined;
  slug?: string | undefined;
};

export const useGetApiV1WebhooksResponse = z.union([
  z.array(
    z.object({
      projectsMetadata: z
        .array(
          z.object({
            id: z.string(),
            name: z.string(),
            framework: z
              .enum([
                "actix-web",
                "angular",
                "ash",
                "astro",
                "axum",
                "blitzjs",
                "brunch",
                "bun",
                "container",
                "create-react-app",
                "django",
                "docusaurus",
                "docusaurus-2",
                "dojo",
                "eleventy",
                "elysia",
                "ember",
                "eve",
                "express",
                "fastapi",
                "fasthtml",
                "fastify",
                "flask",
                "gatsby",
                "go",
                "gridsome",
                "h3",
                "hexo",
                "hono",
                "hugo",
                "hydrogen",
                "ionic-angular",
                "ionic-react",
                "jekyll",
                "koa",
                "mastra",
                "middleman",
                "nestjs",
                "nextjs",
                "nitro",
                "node",
                "nuxtjs",
                "parcel",
                "polymer",
                "preact",
                "python",
                "react-router",
                "redwoodjs",
                "remix",
                "ruby",
                "rust",
                "saber",
                "sanity",
                "sanity-v2",
                "sapper",
                "scully",
                "services",
                "solidstart",
                "solidstart-1",
                "stencil",
                "storybook",
                "svelte",
                "sveltekit",
                "sveltekit-1",
                "tanstack-start",
                "tanstack-start-lovable",
                "umijs",
                "vite",
                "vitepress",
                "vue",
                "vuepress",
                "xmcp",
                "zola",
                "null",
              ])
              .nullable()
              .optional(),
            latestDeployment: z.string().optional(),
          }),
        )
        .nullable(),
      alertRuleIds: z.array(z.string()).optional(),
      events: z.array(
        z.enum([
          "ai-gateway.auto-reload.limit-reached",
          "ai-gateway.balance-depleted",
          "alerts.triggered",
          "botid.anomaly",
          "budget.reached",
          "comment.created",
          "comment.deleted",
          "comment.mentioned",
          "comment.reaction-added",
          "comment.reaction-removed",
          "comment.resolved",
          "comment.unresolved",
          "comment.updated",
          "deployment",
          "deployment-canceled",
          "deployment-check-rerequested",
          "deployment-checks-completed",
          "deployment-error",
          "deployment-prepared",
          "deployment-ready",
          "deployment.blocked",
          "deployment.build-requested",
          "deployment.canceled",
          "deployment.check-rerequested",
          "deployment.checkrun.cancel",
          "deployment.checkrun.start",
          "deployment.checks.failed",
          "deployment.checks.succeeded",
          "deployment.cleanup",
          "deployment.created",
          "deployment.error",
          "deployment.integration.action.cancel",
          "deployment.integration.action.cleanup",
          "deployment.integration.action.start",
          "deployment.promoted",
          "deployment.ready",
          "deployment.rollback",
          "deployment.succeeded",
          "domain-created",
          "domain.auto-renew.changed",
          "domain.certificate.add",
          "domain.certificate.add.failed",
          "domain.certificate.deleted",
          "domain.certificate.renew",
          "domain.certificate.renew.failed",
          "domain.created",
          "domain.dns.records.changed",
          "domain.renewal",
          "domain.renewal.failed",
          "domain.transfer-in.completed",
          "domain.transfer-in.failed",
          "domain.transfer-in.started",
          "edge-config.created",
          "edge-config.deleted",
          "edge-config.items.updated",
          "firewall.attack",
          "firewall.custom-rule-anomaly",
          "firewall.system-rule-anomaly",
          "flag.created",
          "flag.deleted",
          "flag.segment.created",
          "flag.segment.deleted",
          "flag.segment.updated",
          "flag.updated",
          "function.archival-required",
          "function.removal-required",
          "integration-configuration-permission-updated",
          "integration-configuration-removed",
          "integration-configuration-scope-change-confirmed",
          "integration-configuration.permission-upgraded",
          "integration-configuration.removed",
          "integration-configuration.scope-change-confirmed",
          "integration-configuration.transferred",
          "integration-resource.project-connected",
          "integration-resource.project-disconnected",
          "marketplace.invoice.created",
          "marketplace.invoice.notpaid",
          "marketplace.invoice.overdue",
          "marketplace.invoice.paid",
          "marketplace.invoice.refunded",
          "marketplace.member.changed",
          "message.created",
          "message.deleted",
          "message.mentioned",
          "message.reaction-added",
          "message.reaction-removed",
          "message.updated",
          "observability.anomaly",
          "observability.anomaly-error",
          "observability.error-anomaly",
          "observability.usage-anomaly",
          "project-created",
          "project-removed",
          "project.created",
          "project.domain.created",
          "project.domain.deleted",
          "project.domain.moved",
          "project.domain.unverified",
          "project.domain.updated",
          "project.domain.verified",
          "project.env-variable.created",
          "project.env-variable.deleted",
          "project.env-variable.updated",
          "project.removed",
          "project.renamed",
          "project.rolling-release.aborted",
          "project.rolling-release.approved",
          "project.rolling-release.completed",
          "project.rolling-release.started",
          "test-webhook",
          "thread.resolved",
          "thread.unresolved",
        ]),
      ),
      id: z.string(),
      url: z.string(),
      ownerId: z.string(),
      createdAt: z.number(),
      updatedAt: z.number(),
      projectIds: z.array(z.string()).optional(),
    }),
  ),
  z.array(
    z.object({
      alertRuleIds: z.array(z.string()).optional(),
      events: z.array(
        z.enum([
          "ai-gateway.auto-reload.limit-reached",
          "ai-gateway.balance-depleted",
          "alerts.triggered",
          "botid.anomaly",
          "budget.reached",
          "comment.created",
          "comment.deleted",
          "comment.mentioned",
          "comment.reaction-added",
          "comment.reaction-removed",
          "comment.resolved",
          "comment.unresolved",
          "comment.updated",
          "deployment",
          "deployment-canceled",
          "deployment-check-rerequested",
          "deployment-checks-completed",
          "deployment-error",
          "deployment-prepared",
          "deployment-ready",
          "deployment.blocked",
          "deployment.build-requested",
          "deployment.canceled",
          "deployment.check-rerequested",
          "deployment.checkrun.cancel",
          "deployment.checkrun.start",
          "deployment.checks.failed",
          "deployment.checks.succeeded",
          "deployment.cleanup",
          "deployment.created",
          "deployment.error",
          "deployment.integration.action.cancel",
          "deployment.integration.action.cleanup",
          "deployment.integration.action.start",
          "deployment.promoted",
          "deployment.ready",
          "deployment.rollback",
          "deployment.succeeded",
          "domain-created",
          "domain.auto-renew.changed",
          "domain.certificate.add",
          "domain.certificate.add.failed",
          "domain.certificate.deleted",
          "domain.certificate.renew",
          "domain.certificate.renew.failed",
          "domain.created",
          "domain.dns.records.changed",
          "domain.renewal",
          "domain.renewal.failed",
          "domain.transfer-in.completed",
          "domain.transfer-in.failed",
          "domain.transfer-in.started",
          "edge-config.created",
          "edge-config.deleted",
          "edge-config.items.updated",
          "firewall.attack",
          "firewall.custom-rule-anomaly",
          "firewall.system-rule-anomaly",
          "flag.created",
          "flag.deleted",
          "flag.segment.created",
          "flag.segment.deleted",
          "flag.segment.updated",
          "flag.updated",
          "function.archival-required",
          "function.removal-required",
          "integration-configuration-permission-updated",
          "integration-configuration-removed",
          "integration-configuration-scope-change-confirmed",
          "integration-configuration.permission-upgraded",
          "integration-configuration.removed",
          "integration-configuration.scope-change-confirmed",
          "integration-configuration.transferred",
          "integration-resource.project-connected",
          "integration-resource.project-disconnected",
          "marketplace.invoice.created",
          "marketplace.invoice.notpaid",
          "marketplace.invoice.overdue",
          "marketplace.invoice.paid",
          "marketplace.invoice.refunded",
          "marketplace.member.changed",
          "message.created",
          "message.deleted",
          "message.mentioned",
          "message.reaction-added",
          "message.reaction-removed",
          "message.updated",
          "observability.anomaly",
          "observability.anomaly-error",
          "observability.error-anomaly",
          "observability.usage-anomaly",
          "project-created",
          "project-removed",
          "project.created",
          "project.domain.created",
          "project.domain.deleted",
          "project.domain.moved",
          "project.domain.unverified",
          "project.domain.updated",
          "project.domain.verified",
          "project.env-variable.created",
          "project.env-variable.deleted",
          "project.env-variable.updated",
          "project.removed",
          "project.renamed",
          "project.rolling-release.aborted",
          "project.rolling-release.approved",
          "project.rolling-release.completed",
          "project.rolling-release.started",
          "test-webhook",
          "thread.resolved",
          "thread.unresolved",
        ]),
      ),
      id: z.string(),
      url: z.string(),
      ownerId: z.string(),
      createdAt: z.number(),
      updatedAt: z.number(),
      projectIds: z.array(z.string()).optional(),
    }),
  ),
]);

export const getApiV1WebhooksQueryOptions = (args: UseGetApiV1WebhooksArgs) =>
  queryOptions({
    queryKey: ["GET /v1/webhooks", "webhooks", args.projectId, args.teamId, args.slug],
    queryFn: () =>
      apiFetch(
        buildUrl("/v1/webhooks", {
          projectId: args.projectId,
          teamId: args.teamId,
          slug: args.slug,
        }),
        useGetApiV1WebhooksResponse,
        { method: "GET" },
      ),
  });

export const useGetApiV1Webhooks = (args: UseGetApiV1WebhooksArgs) =>
  useQuery(getApiV1WebhooksQueryOptions(args));
